name: app_read
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_mask: ^2.0.1
  pin_code_fields: ^7.4.0
  get: ^4.6.5
  flutter_screenutil: ^5.7.0
  lottie: ^2.4.0
  faker: ^2.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^2.0.0


flutter:
  
  uses-material-design: true

  assets:
    - lib/app/assets/bookLogo.json
